model_type: transformer  # or "lstm"
task: expr                # or "va", "au"

model:
  input_dim: 768
  model_dim: 512          # for transformer
  num_heads: 8            # for transformer
  num_layers: 4
  dropout: 0.1
  # hidden_dim: 256         # for lstm only

train:
  batch_size: 32
  lr: 0.0001
  epochs: 10

data:
  feature_root: data/features/features_mean
  label_root: data/labels
  seq_len: 30
