task: au
model_type: transformer
device: cuda:1

model:
  input_dim: 768
  model_dim: 512
  num_heads: 8
  num_layers: 4
  dropout: 0.1

train:
  batch_size: 32
  lr: 0.0001
  epochs: 5

data:
  feature_root: data/features/image/mean
  label_root: data/labels
  seq_len: 50