## BASIC SETTINGS

# AU, EXPR, VA
task : AU
num_classes : 12
dir : abaw/au/transformer
device : cuda:1

# dataset
data_path : /media/minseongjae/HDD/data/AffWild2/Features
anno_path : /media/minseongjae/HDD/data/AffWild2/6th ABAW Annotations
window_size : 1
stride : 1

# data loader
batch_size : 1024
num_workers : 4

# model
model : transformer
embedding_size : 768
n_layers : 6
n_head : 4

# optimizer
lr : 0.001
optimizer : Adam
use_scheduler : False
step_size : 1000
gamma : 0.99
use_weight_decay : False
decay_rate : 0.001
epoch : 200