## BASIC SETTINGS

# AU, EXPR, VA
task : EXPR
num_classes : 8

device : cuda:0
# dataset
data_path : /media/minseongjae/HDD/data/AffWild2/Features
anno_path : /media/minseongjae/HDD/data/AffWild2/6th ABAW Annotations

# data loader
batch_size : 128
num_workers : 4

# model
seq_len : 1
embedding_size : 768
n_layers : 6
n_head : 8

# optimizer
lr : 0.001
optimizer : Adam
use_scheduler : False
step_size : 1000
gamma : 0.99
use_weight_decay : False
decay_rate : 0.001
epoch : 200