## BASIC SETTINGS

# AU, EXPR, VA
task : EXPR
num_classes : 8
dir : abaw/expr/seq_lstm
device : cuda:0

# dataset
data_path : /home/minseongjae/ABAW/0_data
anno_path : /media/minseongjae/HDD/data/AffWild2/6th ABAW Annotations
seq_size : 1
return_img : False
return_aud : True
return_seq : False
return_vis : False

# data loader
batch_size : 1024
num_workers : 4

# model
model : lstm
embedding_size : 768
n_layers : 6
n_head : 8
# linear model
batch_norm : True
dropout : 0.2

# optimizer
lr : 0.001
optimizer : Adam
use_scheduler : False
step_size : 1000
gamma : 0.99
use_weight_decay : False
decay_rate : 0.001
epoch : 200