## BASIC SETTINGS

# AU, EXPR, VA
task : VA
num_classes : 2
dir : abaw/va/seq
device : cuda:1

# dataset
data_path : /home/minseongjae/ABAW/0_data
anno_path : /media/minseongjae/HDD/data/AffWild2/6th ABAW Annotations
seq_size : 10
return_img : False
return_aud : False
return_seq : True
return_vis : True

# data loader
batch_size : 1024
num_workers : 4

# model
model : transformer
embedding_size : 768
n_layers : 6
n_head : 8

# optimizer
lr : 0.001
optimizer : Adam
use_scheduler : False
step_size : 1000
gamma : 0.99
use_weight_decay : False
decay_rate : 0.001
epoch : 200